spring:
  cloud:
    gateway:
      routes:
        - id: restaurant-service
          uri: lb://RESTAURANT-SERVICE
          predicates:
            - Path=/api/v1/food-delivery-app/restaurants/**
  application:
    name: API-GATEWAY

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/