server:
  port: 9092

spring:
  application:
    name: CATALOG-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/catalogdb
    password: food
    username: food
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
#    register-with-eureka: true
#    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

#server:
#  port: 9092
#
#spring:
#  profiles:
#    active: dev
#
#  application:
#    name: CATALOG-SERVICE
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    database-platform: org.hibernate.dialect.MySQL8Dialect
